-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cookiedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cookiedb` ;

-- -----------------------------------------------------
-- Schema cookiedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cookiedb` DEFAULT CHARACTER SET utf8 ;
USE `cookiedb` ;

-- -----------------------------------------------------
-- Table `cookie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookie` ;

CREATE TABLE IF NOT EXISTS `cookie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `ingredient_list` TEXT NULL,
  `instructions` TEXT NULL,
  `prep_time_minutes` INT NULL,
  `bake_time_minutes` INT NULL,
  `yield` INT NULL,
  `texture` VARCHAR(200) NULL,
  `comment` VARCHAR(5000) NULL,
  `source` VARCHAR(5000) NULL,
  `image_url` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS cookieuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'cookieuser'@'localhost' IDENTIFIED BY 'cookieuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'cookieuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cookie`
-- -----------------------------------------------------
START TRANSACTION;
USE `cookiedb`;
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (1, 'Oatmeal Scotchies', 'Oatmeal Scotchies are a deliciously chewy cookie, with just the right amount of sweetness. ', '1 1/4 cups all-purpose flour * 1 teaspoon baking soda * 1/2 teaspoon salt * 1/2 teaspoon ground cinnamon * 1 cup (2 sticks) butter or margarine, softened * 3/4 cup granulated sugar * 3/4 cup packed brown sugar * 2 large eggs * 1 teaspoon vanilla extract or grated peel of 1 orange * 3 cups quick or old-fashioned oats * 1 2/3 cups (11-ounce package) NESTLÉ® TOLL HOUSE® Butterscotch Flavored Morsels', '1. Preheat oven to 375° F. 2. Combine flour, baking soda, salt and cinnamon in small bowl. Beat butter, granulated sugar, brown sugar, eggs and vanilla extract in large mixer bowl. Gradually beat in flour mixture. Stir in oats and morsels. Drop by rounded tablespoon onto ungreased baking sheets. 3. Bake for 7 to 8 minutes for chewy cookies. Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.', 10, 8, 48, 'chewy', 'Bake for 9 to 10 minutes for a crispier cookie.', 'https://www.verybestbaking.com/toll-house/recipes/oatmeal-scotchies-2/', 'https://www.crazyforcrust.com/wp-content/uploads/2011/05/BEST-Oatmeal-Scotchies-recipe-1.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (2, 'Pumpkin Snickerdoodles', 'These decadent cookies will melt in your mouth.', '1 cup shortening * 1 cup white sugar * ½ cup light brown sugar * ¾ cup pumpkin puree * 1 large egg * 2 teaspoons vanilla extract * 3 ¾ cups all-purpose flour * 1 ½ teaspoons baking powder * 1 ½ teaspoons ground cinnamon * 1 teaspoon cream of tartar * 1 teaspoon salt * ¼ teaspoon ground nutmeg ** Topping: ½ cup white sugar * 1 teaspoon ground cinnamon * ¼ teaspoon allspice', '1. Beat shortening, 1 cup white sugar, and light brown sugar together in a bowl until light and fluffy. Stir in pumpkin puree; beat in eggs and vanilla extract. 2. Whisk flour, baking powder, 1 1/2 teaspoons cinnamon, cream of tartar, salt, and nutmeg together in a bowl. Gradually stir flour mixture into pumpkin mixture until dough is just-combined. Cover the bowl with plastic wrap and refrigerate until chilled, at least 1 hour. 3. Preheat oven to 350 degrees F (175 degrees C). Line baking sheets with parchment paper. 4.  Whisk 1/2 cup white sugar, 1 teaspoon cinnamon, and allspice together in a small bowl. Roll dough into 1-inch balls; roll balls in cinnamon-sugar mixture and place 2 inches apart on prepared baking sheets. Slightly flatten each ball with a flat-bottomed glass. Bake in the preheated oven until golden and set, 12 to 13 minutes. Cool on the baking sheet for 5 minutes before transferring to a wire rack to cool completely.', 15, 15, 24, 'cakey', 'Try a cream cheese glaze to change it up.', 'https://www.allrecipes.com/recipe/239577/pumpkin-snickerdoodles/', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4081843.jpg&w=596&h=596&c=sc&poi=face&q=85');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (3, 'Pfeffernusse', 'A spice cookie with a peppery twist', '1/2 cup butter softened * 3/4 cup light brown sugar * 1/4 cup molasses * 1 egg * 2 1/4 cups all purpose flour * 1/2 teaspoon baking soda * 1/2 teaspoon kosher salt * 1/2 teaspoon cinnamon * 1/2 teaspoon anise seed as finely crushed as possible * 1/2 teaspoon freshly ground black pepper * 1/4 teaspoon ground nutmeg * 1/4 teaspoon ground allspice * 1/8 teaspoon ground cardamom * 1/8 teaspoon ground cloves * 1 1/2 cups powdered sugar ', 'Combine the butter, brown sugar and molasses in a large mixing bowl and beat until smooth. Add the egg and beat to combine. Whisk together the flour, baking soda and all of the spices. Slowly add the dry ingredients to the wet ingredients and beat to combine. Chill the dough in the refrigerator for at least 1 hour. \nPreheat oven to 350 degrees. Scoop about 2 tablespoons of cookie dough and roll into a ball between your palms. Place the dough balls on a parchment or silpat lined baking sheet. Bake for 13-14 minutes, until firm to the touch. Remove from the oven and let the cookies cool on the sheets for 3 minutes. \nPlace the powdered sugar in a medium sized container with a lid. Drop a few cookies at a time into the powdered sugar. Cover with a lid and shake gently to coat. Transfer the coated cookies to a wire cooling rack and let cool completely. Repeat with all the cookies. Store in an airtight container. Enjoy!', 15, 14, 36, 'cakey', NULL, 'https://barefeetinthekitchen.com/pfeffernusse-german-pepper-nut-cookie-recipe/?fbclid=IwAR0DO5piPqs2rqJthZeZYR--SvQ-sbYtH-q-jiTtUf5_4CXRkqWExUTxS-I', 'https://barefeetinthekitchen.com/wp-content/uploads/2013/09/pfeffernusse-cookies-7-small-in-jar-small-331x346.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (4, 'Mexican Wedding Cake Cookies', 'A shortbread base, mixed with nuts, typically pecans, then tossed in powdered sugar.', '1 cup butter * ½ cup white sugar * 2 teaspoons vanilla extract * 2 teaspoons water * 2 cups all-purpose flour * 1 cup chopped almonds * ½ cup confectioners\' sugar', 'Cream together butter and powdered sugar until light and fluffy; stir in vanilla.\\nWhisk together flour and salt; add gradually to butter mixture; stir in chopped nuts.\\nChill dough if it seems too soft.\\nForm dough into 1 1/4\\\" balls and place onto parchment-lined or ungreased baking sheets.\\nBake at 400° for 10-12 minutes or just until the cookies start to turn light golden-brown; remove from oven and allow to cool slightly; while cookies are still warm (but NOT hot) remove them from baking sheets and roll, a few at a time, in powdered sugar until evenly coated; cool cookies completely on wire racks.\\nCookies may (optionally) be rolled in powdered sugar a second time once cooled to room temperature.', 10, 10, 36, 'crispy', 'My favorite cookie!!!', 'https://www.allrecipes.com/recipe/15542/mexican-wedding-cookies/', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F154011.jpg&w=596&h=399&c=sc&poi=face&q=85');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (5, 'Salted Caramel Coconut Thumbprint Cookies', 'These Salted Carmel Coconut Thumbprint Cookies are a modern twist on a classic cookie recipe that makes them perfect for the fall!', '* 3 sticks unsalted butter - softened\n* 1 cup sugar\n* 1 1/2 teaspoons vanilla\n* 3 cups all-purpose flour\n* 1/2 teaspoon kosher salt\n* 3 large eggs - lightly beaten\n* 12 ounces sweetened flaked coconut\n* 1 bag (about 14 ounces) soft caramel candies\n* 6 tablespoons heavy cream\n* 2 tablespoons flaky sea salt', 'Begin by preheating your oven to 350 degrees F.\nIn a large bowl, beat together your butter and sugar with a mixer on medium speed until light and fluffy (about 3 minutes); then beat in the vanilla and salt. With the mixer on low, gradually add the flour and beat until just combined.\nRoll the dough with your hands into 1-inch balls.\nThen, in one small bowl place your lightly beaten eggs. In another small bowl, place your coconut. Dip each ball first in the egg, then roll in the coconut.\nPlace balls on a parchment-lined baking sheet. Press an indentation into each ball with your thumb, finger, or back of a wooden spoon. Bake for 10 minutes. Remove the cookies from the oven and re-press the indentations. (Use caution since the cookies are hot.) Place the cookies back in the oven for an additional 10 minutes or until the cookies and coconut are golden.\nRemove and let cool on a wire rack.\nNow, place the unwrapped caramels and heavy cream in a sauce pan over low heat. Stir constantly until the caramels are melted and the mixture is smooth. Spoon the caramel sauce into the cookie indentations. Then, sprinkle with sea salt.', 15, 10, 36, 'chewy', NULL, 'https://inspiredbycharm.com/salted-caramel-coconut-thumbprints-cookies/', 'https://inspiredbycharm-wpengine.netdna-ssl.com/wp-content/uploads/2014/09/caramel-thumprint-cookies.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (6, 'White Chocolate Cherry Macadamia Cookies', 'Buttery, chewy, delightful.  Prepare to fall in love… These are also the perfect cookies to make for the Holidays.  You can use either dried cherries or cranberries.', '½ cup butter, softened * ½ cup packed brown sugar * ½ cup white sugar * 1 egg * 1 teaspoon vanilla extract * 1½ cups all-purpose flour * ½ teaspoon baking soda * ¼ teaspoon salt * ¾ cup white chocolate chips * ½ cup chopped macadamia nuts * 1 cup dried cherries', '1. Preheat oven to 375 F. Grease a cookie sheet. 2. In a large mixing bowl, combine the butter and sugars. Using an electric mixer, cream the butter and sugars until fluffy and pale in color, 3-5 minutes. This step is important for ensuring soft, chewy cookies. Beat in the egg and vanilla extract. 3. In a separate bowl, combine the flour, baking soda and salt. Using a wooden spoon, carefully stir the flour mixture into the butter mixture, just until combined. Stir in the white chocolate chips, dried cherries and macadamia nuts. 4. Drop heaping spoonfuls of the batter onto the greased cookie sheet. 5. Bake the cookies for 8-10 minutes or until they just begin to turn golden around the edges. Allow the cookies to cool for 2 minutes on the cookie sheet before transferring them to a wire rack to cool completely. 6. *Note: It isn\'t necessary for this recipe (I personally prefer the cherries to be chewy), but you can optionally place the dried cherries in a bowl and cover them with boiling water to soften them. Let them soak for 7-8 then thoroughly drain them. If you choose to soak them, use only ½-3/4 cup dried cherries as they will expand.', 10, 10, 24, 'chewy', 'Haven\'t tried them yet, but they look delicious!', 'https://www.daringgourmet.com/white-chocolate-cherry-macadamia-cookies/', 'https://www.daringgourmet.com/wp-content/uploads/2013/02/Cookies-9-sm.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (7, 'Oatmeal Raisin Cookies', 'The cookie that is tasty but still tricks everyone!', '1 cup (1/2 pound or 2 sticks) unsalted butter, softened, OR 1 cup shortening\n1 cup brown sugar, packed\n1/2 cup plus 2 tablespoons granulated sugar\n2 large eggs\n1 tablespoon vanilla extract\n1 1/2 cups all-purpose flour\n3/4 teaspoon salt\n1 teaspoon baking soda\n1 teaspoon ground cinnamon\n1/2 teaspoon freshly grated nutmeg\n1 1/2 cups raisins\n1/2 cup chopped walnuts (optional)\n3 cups rolled oats (We use Quaker Old Fashioned or Quick. Do NOT use instant.)', '1 Preheat and prep: Preheat oven to 350°F. Grease two large cookie sheets or line with Silpat or parchment paper.\n\n2 Combine the butter, sugar and eggs: In a large mixing bowl, beat butter until creamy. Add the brown sugar and white sugar, beat until fluffy, about 3 minutes. Beat in eggs, one at a time. Add the vanilla extract.\n\n3 Add the dry ingredients: Mix flour, salt, baking soda, cinnamon, and nutmeg together in medium bowl. Stir the dry ingredients into the butter-sugar mixture. Stir in the raisins and nuts. Stir in the oats.\n\n4 Scoop out the dough onto sheets: Spoon out the dough by large tablespoonfuls onto the prepared cookie sheets, leaving at least 2 inches between each cookie.\n\n5 Bake the cookies: Bake until the edges of the cookies turn golden brown, about 10 to 12 minutes. Note that the cookies will seem underdone and lightly colored everywhere but the edges. That\'s okay, they will firm up as they cool.\n\n6 Cool, transfer, and store: Cool 1 minute on cookie sheets. Then carefully remove them, using a metal spatula, to a wire rack. Cool completely. They will be quite soft until completely cooled. Store tightly covered.', 20, 12, 24, 'chewy', 'Do not overbake these cookies! The edges should be brown, but the rest of the cookie should be very light in color.', 'https://www.simplyrecipes.com/recipes/oatmeal_raisin_cookies/', 'https://www.simplyrecipes.com/wp-content/uploads/2008/03/oatmeal-raisin-cookies-horiz-a-1800.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (8, 'Chocolate Crinkle Cookies', 'These crinkle cookies stand out from the pack with chocolate goodness throughout.   Coated with lots of powered sugar and baked until perfectly chewy, what’s not to love?  Don’t these look great!', '1 cup unsweetened cocoa powder\n2 cups white sugar\n1/2 cup vegetable oil\n4 large eggs\n2 teaspoons vanilla extract\n2 cups (8.5 ounces or 240 grams) all-purpose flour\n2 teaspoons baking powder\n½ teaspoon salt\n3/4 cup confectioner’s sugar (powdered sugar)', 'In a medium bowl, mix together cocoa, white sugar, and vegetable oil. Beat in eggs one at a time, then stir in the vanilla.  In another bowl, combine the flour, baking powder, and salt.  Stir the flour mixture into the cocoa mixture. Cover dough, and chill for at least 4 hours or freeze for about 45 minutes.\n\nLine 2 large cookie sheets with parchment paper.  Preheat oven to 350 degrees F (175 degrees C).  Put 3/4 cup powdered sugar in a small saucer and set aside.\nForm cookies by rolling dough into one inch balls or use a number 50-size scoop.  You can also use spoons to scoop the dough up.  Drop dough balls DIRECTLY into the powdered sugar.  Roll to coat each ball thoroughly in the powdered sugar to ensure good crinkling.  Place balls on prepared cookie sheets.\nBake in preheated oven for 10 to 12 minutes. Let stand on the cookie sheet for a minute before transferring to wire racks to cool.', 20, 12, 40, 'cakey', NULL, 'https://www.alohadreams.com/chocolate-crinkle-cookies/', 'https://www.alohadreams.com/wp-content/uploads/2017/05/chocolate_crinkle_cookies.jpg');
INSERT INTO `cookie` (`id`, `name`, `description`, `ingredient_list`, `instructions`, `prep_time_minutes`, `bake_time_minutes`, `yield`, `texture`, `comment`, `source`, `image_url`) VALUES (9, 'Shortbread Cookies', 'This shockingly easy, crisp, melt in your mouth shortbread cookies recipe comes together with five ingredients you probably have in your pantry!', '10 tbsp unsalted butter unsalted butter, at room temperature 142g 1/2 cup confectioners\' sugar 1/2 teaspoon pure vanilla extract 1 1/2 cups all-purpose flour 180g 1/2 teaspoon kosher salt optional', 'In a stand mixer fitted with a paddle attachment, beat butter and vanilla extract until creamed.\nAdd confectioners sugar and salt; mix until combined.\nScrape bowl down and add flour while beating on low. Scrape bowl once more and mix until combined.\nShape the dough into a rectangular prism, wrap in plastic and chill until firm. At least an hour.\nPreheat oven to 350F (177C). Use a sharp knife to cut 1/2 inch thick slices\nPlace slices, spaced at least an inch apart onto a baking sheet lined with a silicone mat or parchment paper.\nUse a fork or skewer to indent a pattern onto the top.\nBake for about 10 minutes, rotating baking sheet in the oven halfway through.\nTransfer to a wire sheet to cool.', 15, 20, 16, 'short', NULL, 'https://preppykitchen.com/shortbread-cookies-recipe/', 'https://preppykitchen.com/wp-content/uploads/2019/06/Shortbread-cookies-Blog.jpg');

COMMIT;

